CRITICAL - 2021-11-24 23:48:30 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\bitirmeProjesi-Ci\app\Views\Frontend\DuyurularView.php(25): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\bitirmeProjesi-Ci\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Common.php(1097): CodeIgniter\View\View->render('Frontend/Duyuru...', Array, true)
#4 C:\xampp\htdocs\bitirmeProjesi-Ci\app\Controllers\Frontend\Home.php(44): view('Frontend/Duyuru...', Array)
#5 C:\xampp\htdocs\bitirmeProjesi-Ci\system\CodeIgniter.php(824): App\Controllers\Frontend\Home->duyurular('tr')
#6 C:\xampp\htdocs\bitirmeProjesi-Ci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Frontend\Home))
#7 C:\xampp\htdocs\bitirmeProjesi-Ci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\bitirmeProjesi-Ci\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-11-24 23:48:30 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:23 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:23 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:23 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:23 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:24 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:24 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:24 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:24 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:24 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:24 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:24 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:26 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:26 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:26 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:27 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:27 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:27 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:27 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:27 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:27 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:27 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:27 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:38 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:38 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:38 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:38 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:38 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:38 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:38 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:38 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:38 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:38 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:38 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:52 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:52 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:52 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:52 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:52 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:52 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:52 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:53 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:53 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:53 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:50:53 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:25 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:25 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:25 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:25 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:25 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:25 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:25 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:25 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:25 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:25 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:25 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:26 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:26 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:26 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:26 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:26 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:26 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:27 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:27 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:27 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:27 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:27 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:27 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:27 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:27 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:27 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:27 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:27 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:27 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:27 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:27 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:27 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:27 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:28 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:28 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:28 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:28 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:28 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:28 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:28 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:28 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:28 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:28 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:28 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:28 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:28 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:28 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:28 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:28 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:28 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:28 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:28 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:28 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:29 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:29 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:29 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:29 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:29 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:29 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:29 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:29 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:29 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:29 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:29 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:29 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:29 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:30 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:30 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:30 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:30 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:30 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:30 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:30 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:30 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:30 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:30 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-24 23:51:30 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\bitirmeProjesi-Ci\app\Config\Events.php:32) in C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 107, Array)
#1 C:\xampp\htdocs\bitirmeProjesi-Ci\system\Debug\Exceptions.php(107): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
